"""Add task_content to tasks

Revision ID: c3af4990f4c4
Revises: c44015fd6b3a
Create Date: 2026-04-09 10:46:30.286244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3af4990f4c4'
down_revision: Union[str, Sequence[str], None] = 'c44015fd6b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_content', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_content')
    # ### end Alembic commands ###
